language: node_js

node_js:
  - "stable"

env:
  global:
    - CODECLIMATE_REPO_TOKEN=bb4bc94f945f1cdf63074c6788fe31b9eb2521e7f4a0b742110825c41d78c729

install:
  - npm install

cache:
  directories:
    - "node_modules"


after_success:
  - npm run coverage
